### ISSUE TITLE
Responses per survey on this page says 50,000 which doesn't match elsewhere

### ISSUE THREAD

**Issue by sjackson-ag** [MicrosoftDocs/customer-voice#50]
The 50,000 responses per survey on this page is contradicted by the 500,000 responses per page which is listed on.
https://docs.microsoft.com/en-us/dynamics365/customer-voice/plan-survey#survey-question-response-and-character-limits

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e270f9b-420e-4638-2f97-2d89d119d3fa
* Version Independent ID: 57f68427-8967-1489-543a-fd39e77018ca
* Content: [Plan a survey](https://docs.microsoft.com/en-gb/dynamics365/customer-voice/plan-survey#survey-question-response-and-character-limits)
* Content Source: [cv-docs/plan-survey.md](https://github.com/MicrosoftDocs/customer-voice/blob/main/cv-docs/plan-survey.md)
* Service: **dynamics-365-customervoice**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by sbmjais** [comment]
@sjackson-ag - Thanks for contacting us. I have forwarded your feedback to the technical team. The 50,000 limit is a restriction on the UI, hence the same is captured in the document. The limit will be fixed in the future releases. We'll update the document accordingly. The current response limit is 500,000, that's mentioned at: [https://docs.microsoft.com/en-us/dynamics365/customer-voice/plan-survey#survey-question-response-and-character-limits](https://docs.microsoft.com/en-us/dynamics365/customer-voice/plan-survey#survey-question-response-and-character-limits)
Closing this task.
